FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["Ryshin.Cdn/Ryshin.Cdn.csproj", "Ryshin.Cdn/"]
RUN dotnet restore "Ryshin.Cdn/Ryshin.Cdn.csproj"
COPY . .
WORKDIR "/src/Ryshin.Cdn"
RUN dotnet build "Ryshin.Cdn.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Ryshin.Cdn.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Ryshin.Cdn.dll"]